### ISSUE TITLE
Description-related bug in islandora_context_reaction_display_solr_metadata

### ISSUE THREAD

**Issue by bradspry** [SFULibrary/islandora_context#6]
Islandora Context is not respecting the Description configuration as set in solr_metadata_configuration.

Recorded screencast to best demonstrate the bug:
http://screencast.com/t/fk1bXITg

**Comment by mjordan** [comment]
@bradspry, :+1:  on using a screencast as bug report/how to replicate.

Thanks for reporting, I'll try to investigate by the end of the week.

**Comment by mjordan** [comment]
@bradspry I've added a "Use the corresponding Islandora Solr Metadata description" reaction to the issue-6 branch. Note that you must choose the "Use an Islandora Solr Metadata configuration" reaction and this new one separately. The "Use the corresponding Islandora Solr Metadata description" reaction does not use an options form (it gets associated with the selected metadata display automatically).  Let me know if it does what you expect.

Having to choose the two related reactions separately is awkward, but I don't see how I can implement this any other way, since the Solr metadata configuration and the description are themed separately, and Context reactions can only return the output from one theming function.

**Comment by bradspry** [comment]
@mjordan Yes Sir, you've done it, it works as expected!   

The smile on my Metadata Librarian's face this morning when he saw his vision and configuration come to life was priceless :-D

**Comment by mjordan** [comment]
Excellent. I'll merge that branch into 7.x later today.

**Comment by mjordan** [comment]
Merged. Thanks for helping with this @bradspry.

**Comment by bradspry** [comment]
Thank You Very Much @mjordan 

Beyond words, I really appreciate your hard work!!!

"Mark" of Excellence!!!
